spring.application.name=qedu

spring.datasource.url=jdbc:postgresql://localhost:5432/qedu
spring.datasource.username=dani2000
spring.datasource.password=dragon55

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=http://localhost:3000

spring.profiles.active=dev